substitutions:
  name: kc868-a8

esphome:
  name: ${name}
  name_add_mac_suffix: true
  project:
    name: kincony.kc868-a8
    version: "1"

esp32:
  board: esp32dev

web_server:
  port: 80

dashboard_import:
  package_import_url: github://hzkincony/kc868-a8/kc868-a8.yaml@main

ota:
  password: "bobthebuilder"

# I2C / ETH as you had them
i2c:
  sda: 4
  scl: 5
  scan: true
  id: bus_a

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0

# PCF8574 expanders (outputs at 0x24, inputs at 0x22)
pcf8574:
  - id: pcf8574_hub_out_1   # outputs 1–8
    address: 0x24
  - id: pcf8574_hub_in_1    # inputs 1–8
    address: 0x22

# Relays (give each one an id so inputs can reference them)
switch:
  - platform: gpio
    id: relay1
    name: "light1"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 0
      mode: OUTPUT
      inverted: true

  - platform: gpio
    id: relay2
    name: "light2"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 1
      mode: OUTPUT
      inverted: true

  - platform: gpio
    id: relay3
    name: "light3"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 2
      mode: OUTPUT
      inverted: true

  - platform: gpio
    id: relay4
    name: "light4"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 3
      mode: OUTPUT
      inverted: true

  - platform: gpio
    id: relay5
    name: "light5"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 4
      mode: OUTPUT
      inverted: true

  - platform: gpio
    id: relay6
    name: "light6"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 5
      mode: OUTPUT
      inverted: true

  - platform: gpio
    id: relay7
    name: "light7"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 6
      mode: OUTPUT
      inverted: true

  - platform: gpio
    id: relay8
    name: "light8"
    pin:
      pcf8574: pcf8574_hub_out_1
      number: 7
      mode: OUTPUT
      inverted: true

# Inputs with debouncing + automations
binary_sensor:
  # Input1: TOGGLE Relay1 on each active edge
  - platform: gpio
    id: input1
    name: "input1"
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 0
      mode: INPUT
      inverted: true
    filters:
      - delayed_on_off: 20ms
    on_press:
      - switch.toggle: relay1

  # Input2: MIRROR Relay2 (on when input on, off when input off)
  - platform: gpio
    id: input2
    name: "input2"
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 1
      mode: INPUT
      inverted: true
    filters:
      - delayed_on_off: 20ms
    on_press:
      - switch.turn_on: relay2
    on_release:
      - switch.turn_off: relay2

  # Input3: PULSE Relay3 for 500 ms when pressed
  - platform: gpio
    id: input3
    name: "input3"
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 2
      mode: INPUT
      inverted: true
    filters:
      - delayed_on_off: 20ms
    on_press:
      - switch.turn_on: relay3
      - delay: 500ms
      - switch.turn_off: relay3

  # Inputs 4–8 (no actions yet—copy one of the patterns above if you want)
  - platform: gpio
    id: input4
    name: "input4"
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 3
      mode: INPUT
      inverted: true
    filters:
      - delayed_on_off: 20ms

  - platform: gpio
    id: input5
    name: "input5"
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 4
      mode: INPUT
      inverted: true
    filters:
      - delayed_on_off: 20ms

  - platform: gpio
    id: input6
    name: "input6"
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 5
      mode: INPUT
      inverted: true
    filters:
      - delayed_on_off: 20ms

  - platform: gpio
    id: input7
    name: "input7"
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 6
      mode: INPUT
      inverted: true
    filters:
      - delayed_on_off: 20ms

  - platform: gpio
    id: input8
    name: "input8"
    pin:
      pcf8574: pcf8574_hub_in_1
      number: 7
      mode: INPUT
      inverted: true
    filters:
      - delayed_on_off: 20ms

# Enable logging / API
logger:
api:
