name: Build & Publish ESPHome Web Installer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build your firmware + create a complete ESP Web Tools manifest
      - name: Build firmware (complete manifest)
        id: build
        uses: esphome/build-action@v7
        with:
          yaml-file: kc868-a8.yaml     # <-- your YAML filename
          complete-manifest: true

      - name: Prepare static site
        run: |
          NAME="${{ steps.build.outputs.name }}"   # e.g., kc868-a8-ESP32
          mkdir -p site/"$NAME"
          cp "$NAME"/* site/"$NAME"/
          cat > site/index.html <<'HTML'
          <!doctype html>
          <html>
          <head>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width,initial-scale=1" />
            <title>KC868-A8 Web Installer</title>
          </head>
          <body>
            <h1>KC868-A8 Web Installer</h1>
            <p>Connect your board via USB (Chrome/Edge desktop), then click Install.</p>
            <esp-web-install-button manifest="./REPLACEME/manifest.json"></esp-web-install-button>
            <script type="module" src="https://unpkg.com/esp-web-tools@10/dist/web/install-button.js?module"></script>
          </body>
          </html>
          HTML
          sed -i "s#REPLACEME#$NAME#g" site/index.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
